plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - Pee N Pee - Homebrewed DnD with Omo Elements & rules.md
  - Character Bladder Rules.md
  - Holders Campaign Rules.md
  - Pissers Campaign Rules.md
  - Bladder Buster Campaign Rules.md
  - Homebrewed material.md
  - LICENSE.md

  theme: jekyll-theme-midnight
